Vision globale des 4 datasets choisis sur les 11 datasets du sujet.

In [2]:
import pandas as pd
from pathlib import Path

files = list(Path("../data/raw").glob("*"))

for f in files:
    print("="*80)
    print("Nom :", f.name)
    
    if f.suffix == ".csv":
        try:
            df = pd.read_csv(f, nrows=5)  # tentative en UTF-8 par défaut
        except UnicodeDecodeError:
            df = pd.read_csv(f, sep=';', encoding="latin1", nrows=5)
        
    elif f.suffix == ".xlsx":
        try:
            df = pd.read_excel(f, nrows=5)
        except Exception as e:
            print(f"Erreur lors de la lecture du fichier {f.name} : {e}")
    else:
        continue
        
    print("Colonnes :", df.columns.tolist())
    print("Nb colonnes :", len(df.columns))
    print()

================================================================================
Nom : 20190308-years.csv
Colonnes : ['media_type', 'channel_name', 'is_public_channel', 'year', 'women_expression_rate', 'speech_rate', 'nb_hours_analyzed']
Nb colonnes : 7

================================================================================
Nom : les-francais-et-l-information-arcom-2024-base-anonymisee.xlsx
Colonnes : ['RECORD', 'UUID', 'CIBLE', 'SOURCE_BASE_R1', 'POIDS03', 'INTER', 'CONTACT', 'RS1_R', 'RS2C_RECODE_AG_R', 'RS3_R', 'RS4_R', 'CSPIND_R', 'RS5_R', 'UDA9_R', 'UDA5_R', 'DPT_DOM_R', 'CC_R', 'RS7_R', 'RS14_R', 'ILLECTRO_R', 'RS15_R', 'FREQ_INTERNET_R', 'RS16_R_1', 'RS16_R_2', 'RS16_R_3', 'RS16_R_4', 'RS16_R_5', 'RS16_R_6', 'RS16_R_7', 'RS16_R_8', 'RS16_R_9', 'RS16_R_10', 'RS16_R_11', 'RS16_R_12', 'RS16_R1_1', 'RS16_R1_2', 'RS16_R1_3', 'RS16_R1_4', 'RS16_R1_5', 'RS16_R1_6', 'RS16_R1_7', 'RS16_R1_8', 'RS16_R1_9', 'RS16_R1_10', 'RS16_R1_11', 'RS16_R1_12', 'RS16_R1_13', 'RS16_R2_1', 'RS16_R2_2', 'RS16_R2_3', 'RS16_R2_4', 'RS16_R2_5', 'RS16_R2_6', 'RS16_R2_7', 'RS16_R2_8', 'RS16_R2_9', 'RS16_R2_10', 'RS16_R2_11', 'RS16_R2_12', 'RS16_R2_13', 'RS16_R3_1', 'RS16_R3_2', 'RS16_R3_3', 'RS16_R3_4', 'RS16_R3_5', 'RS16_R3_6', 'RS16_R3_7', 'RS16_R3_8', 'RS16_R3_9', 'RS16_R3_10', 'RS16_R3_11', 'RS16_R3_12', 'RS16_R3_13', 'INT1_R', 'INT2_R_1', 'INT2_R_2', 'INT2_R_3', 'INT2_R_4', 'INT2_R_5', 'INT2_R_6', 'INT2_R_7', 'INT2_R_8', 'INT2_R_9', 'INT2_R_10', 'INT2_R_11', 'INT2_R_12', 'INT2_R1_1', 'INT2_R1_2', 'INT2_R1_3', 'INT2_R1_4', 'INT2_R1_5', 'INT2_R1_6', 'INT2_R1_7', 'INT2_R1_8', 'INT2_R1_9', 'INT2_R1_10', 'INT2_R1_11', 'INT2_R1_12', 'INT2_R1_13', 'INT2_R2_1', 'INT2_R2_2', 'INT2_R2_3', 'INT2_R2_4', 'INT2_R2_5', 'INT2_R2_6', 'INT2_R2_7', 'INT2_R2_8', 'INT2_R2_9', 'INT2_R2_10', 'INT2_R2_11', 'INT2_R2_12', 'INT2_R2_13', 'INT2_R3_1', 'INT2_R3_2', 'INT2_R3_3', 'INT2_R3_4', 'INT2_R3_5', 'INT2_R3_6', 'INT2_R3_7', 'INT2_R3_8', 'INT2_R3_9', 'INT2_R3_10', 'INT2_R3_11', 'INT2_R3_12', 'INT2_R3_13', 'INT2_R4_1', 'INT2_R4_2', 'INT2_R4_3', 'INT2_R4_4', 'INT2_R4_5', 'INT2_R4_6', 'INT2_R4_7', 'INT2_R4_8', 'INT2_R4_9', 'INT2_R4_10', 'INT2_R4_11', 'INT2_R4_12', 'INT2_R4_13', 'INT2_R5_1', 'INT2_R5_2', 'INT2_R5_3', 'INT2_R5_4', 'INT2_R5_5', 'INT2_R5_6', 'INT2_R5_7', 'INT2_R5_8', 'INT2_R5_9', 'INT2_R5_10', 'INT2_R5_11', 'INT2_R5_12', 'INT2_R5_13', 'INT2_R6_1', 'INT2_R6_2', 'INT2_R6_3', 'INT2_R6_4', 'INT2_R6_5', 'INT2_R6_6', 'INT2_R6_7', 'INT2_R6_8', 'INT2_R6_9', 'INT2_R6_10', 'INT2_R6_11', 'INT2_R6_12', 'INT2_R6_13', 'VERSION_QUESTIO_R', 'INT3_R_1', 'INT3_R_2', 'INT3_R_3', 'INT3_R_4', 'INT3_R_5', 'INT3_R_6', 'INT3_R_7', 'INT3_R_8', 'INT3_R_9', 'INT3_R_10', 'INT3_R_11', 'INT3_R_12', 'INT3_R1_1', 'INT3_R1_2', 'INT3_R1_3', 'INT3_R1_4', 'INT3_R1_5', 'INT3_R1_6', 'INT3_R1_7', 'INT3_R1_8', 'INT3_R1_9', 'INT3_R1_10', 'INT3_R1_11', 'INT3_R1_12', 'INT3_R2_1', 'INT3_R2_2', 'INT3_R2_3', 'INT3_R2_4', 'INT3_R2_5', 'INT3_R2_6', 'INT3_R2_7', 'INT3_R2_8', 'INT3_R2_9', 'INT3_R2_10', 'INT3_R2_11', 'INT3_R2_12', 'INT3_R3_1', 'INT3_R3_2', 'INT3_R3_3', 'INT3_R3_4', 'INT3_R3_5', 'INT3_R3_6', 'INT3_R3_7', 'INT3_R3_8', 'INT3_R3_9', 'INT3_R3_10', 'INT3_R3_11', 'INT3_R3_12', 'INT3_R4_1', 'INT3_R4_2', 'INT3_R4_3', 'INT3_R4_4', 'INT3_R4_5', 'INT3_R4_6', 'INT3_R4_7', 'INT3_R4_8', 'INT3_R4_9', 'INT3_R4_10', 'INT3_R4_11', 'INT3_R4_12', 'INT3_R5_1', 'INT3_R5_2', 'INT3_R5_3', 'INT3_R5_4', 'INT3_R5_5', 'INT3_R5_6', 'INT3_R5_7', 'INT3_R5_8', 'INT3_R5_9', 'INT3_R5_10', 'INT3_R5_11', 'INT3_R5_12', 'INT3_R7', 'INT3_R6_1', 'INT3_R6_2', 'INT3_R6_3', 'INT3_R6_4', 'INT3_R6_5', 'INT3_R6_6', 'INT3_R6_7', 'INT3_R6_8', 'INT3_R6_9', 'INT3_R6_10', 'INT3_R6_11', 'INT3_R6_12', 'MOTIV_R_1', 'MOTIV_R_2', 'MOTIV_R_3', 'MOTIV_R_4', 'MOTIV_R_5', 'MOTIV_R_6', 'MOTIV_R_7', 'MOTIV_R_8', 'MOTIV_R_9', 'MOTIV_R_10', 'MOTIV_R_11', 'MOTIV_R_12', 'MOTIV_R_13', 'MOTIV_R_14', 'MOTIV_R1', 'MOTIV_R2_1', 'MOTIV_R2_2', 'MOTIV_R2_3', 'MOTIV_R2_4', 'MOTIV_R2_5', 'MOTIV_R2_6', 'MOTIV_R2_7', 'MOTIV_R2_8', 'MOTIV_R2_9', 'MOTIV_R2_10', 'MOTIV_R2_11', 'MOTIV_R2_12', 'MOTIV_R2_13', 'MOTIV_R2_14', 'MOTIV_R2_15', 'NEWS1_R_1', 'NEWS1_R_2', 'NEWS1_R_3', 'NEWS1_R_4', 'NEWS1_R_5', 'NEWS1_R_6', 'NEWS1_R_7', 'NEWS1_R_8', 'NEWS1_R1_1', 'NEWS1_R1_2', 'NEWS1_R1_3', 'NEWS1_R1_4', 'NEWS1_R1_5', 'NEWS1_R1_6', 'NEWS1_R1_7', 'NEWS1_R1_8', 'NEWS1_R1_9', 'NEWS1_R2_1', 'NEWS1_R2_2', 'NEWS1_R2_3', 'NEWS1_R2_4', 'NEWS1_R2_5', 'NEWS1_R2_6', 'NEWS1_R2_7', 'NEWS1_R2_8', 'NEWS1_R2_9', 'NEWS1_1B_R', 'NEWS1_2B_R', 'NEWS1_3B_R', 'NEWS1SOURCES_LR6_R', 'NEWS1SOURCES_LR7_R', 'NEWS1SOURCES_LR8_R', 'NEWS1SOURCES_LR9_R', 'NEWS1SOURCES_R_1', 'NEWS1SOURCES_R_2', 'NEWS1SOURCES_R_3', 'NEWS1SOURCES_R_4', 'NEWS1SOURCES_R_5', 'NBR_NEWS1SOURCES_R1', 'NEWS1SOURCES_R2_1', 'NEWS1SOURCES_R2_2', 'NEWS1SOURCES_R2_3', 'NEWS1SOURCES_R2_4', 'NEWS1SOURCES_R2_5', 'NBR_NEWS1SOURCES_R3', 'NEWS1BIS_R', 'DEVICEXMOMENTS_R_1', 'DEVICEXMOMENTS_R_2', 'DEVICEXMOMENTS_R_3', 'DEVICEXMOMENTS_R_4', 'DEVICEXMOMENTS_R_5', 'DEVICEXMOMENTS_R_6', 'DEVICEXMOMENTS_R_7', 'DEVICEXMOMENTS_R_8', 'DEVICEXMOMENTS_R1_1_1', 'DEVICEXMOMENTS_R1_1_2', 'DEVICEXMOMENTS_R1_1_3', 'DEVICEXMOMENTS_R1_1_4', 'DEVICEXMOMENTS_R1_1_5', 'DEVICEXMOMENTS_R1_1_6', 'DEVICEXMOMENTS_R1_1_7', 'DEVICEXMOMENTS_R1_1_8', 'DEVICEXMOMENTS_R1_2_1', 'DEVICEXMOMENTS_R1_2_2', 'DEVICEXMOMENTS_R1_2_3', 'DEVICEXMOMENTS_R1_2_4', 'DEVICEXMOMENTS_R1_2_5', 'DEVICEXMOMENTS_R1_2_6', 'DEVICEXMOMENTS_R1_2_7', 'DEVICEXMOMENTS_R1_2_8', 'DEVICEXMOMENTS_R1_3_1', 'DEVICEXMOMENTS_R1_3_2', 'DEVICEXMOMENTS_R1_3_3', 'DEVICEXMOMENTS_R1_3_4', 'DEVICEXMOMENTS_R1_3_5', 'DEVICEXMOMENTS_R1_3_6', 'DEVICEXMOMENTS_R1_3_7', 'DEVICEXMOMENTS_R1_3_8', 'DEVICEXMOMENTS_R1_4_1', 'DEVICEXMOMENTS_R1_4_2', 'DEVICEXMOMENTS_R1_4_3', 'DEVICEXMOMENTS_R1_4_4', 'DEVICEXMOMENTS_R1_4_5', 'DEVICEXMOMENTS_R1_4_6', 'DEVICEXMOMENTS_R1_4_7', 'DEVICEXMOMENTS_R1_4_8', 'DEVICEXMOMENTS_R1_5_1', 'DEVICEXMOMENTS_R1_5_2', 'DEVICEXMOMENTS_R1_5_3', 'DEVICEXMOMENTS_R1_5_4', 'DEVICEXMOMENTS_R1_5_5', 'DEVICEXMOMENTS_R1_5_6', 'DEVICEXMOMENTS_R1_5_7', 'DEVICEXMOMENTS_R1_5_8', 'DEVICEXMOMENTS_R1_6_1', 'DEVICEXMOMENTS_R1_6_2', 'DEVICEXMOMENTS_R1_6_3', 'DEVICEXMOMENTS_R1_6_4', 'DEVICEXMOMENTS_R1_6_5', 'DEVICEXMOMENTS_R1_6_6', 'DEVICEXMOMENTS_R1_6_7', 'DEVICEXMOMENTS_R1_6_8', 'DEVICEXMOMENTS_R1_7_1', 'DEVICEXMOMENTS_R1_7_2', 'DEVICEXMOMENTS_R1_7_3', 'DEVICEXMOMENTS_R1_7_4', 'DEVICEXMOMENTS_R1_7_5', 'DEVICEXMOMENTS_R1_7_6', 'DEVICEXMOMENTS_R1_7_7', 'DEVICEXMOMENTS_R1_7_8', 'FORMAT_R_1', 'FORMAT_R_2', 'FORMAT_R_3', 'FORMAT_R_4', 'FORMAT3_LR1_FORMAT3_1_R', 'FORMAT2_LR1_FORMAT2_1_R', 'FORMAT3_LR2_FORMAT3_2_R', 'FORMAT3_LR3_FORMAT3_3_R', 'FORMAT2_LR3_FORMAT2_3_R', 'PAY_R_1', 'PAY_R_2', 'PAY_R_3', 'PAY_R_4', 'PAY_R_5', 'PAY_R_6', 'PAY_R_7', 'PAY_R1_1', 'PAY_R1_2', 'PAY_R1_3', 'PAY_R1_4', 'PAY_R1_5', 'PAY_R1_6', 'PAY_R1_7', 'PAY_R1_8', 'AGREG_R_1', 'AGREG_R_2', 'AGREG_R_3', 'AGREG_R_4', 'AGREG_R_5', 'AGREG_R_6', 'AGREG_R_7', 'AGREG_R_8', 'AGREG_R1_1', 'AGREG_R1_2', 'AGREG_R1_3', 'AGREG_R1_4', 'AGREG_R1_5', 'AGREG_R1_6', 'AGREG_R1_7', 'AGREG_R1_8', 'AGREG_R1_9', 'AGREG_R2_1', 'AGREG_R2_2', 'AGREG_R2_3', 'AGREG_R2_4', 'AGREG_R2_5', 'AGREG_R2_6', 'AGREG_R2_7', 'AGREG_R2_8', 'AGREG_R2_9', 'AGREG_R3_1', 'AGREG_R3_2', 'AGREG_R3_3', 'AGREG_R3_4', 'AGREG_R3_5', 'AGREG_R3_6', 'AGREG_R3_7', 'AGREG_R3_8', 'AGREG_R3_9', 'NOTIF_R', 'RSINFO_1_LR_R_1', 'RSINFO_1_LR_R_2', 'RSINFO_1_LR_R_3', 'RSINFO_1_LR_R_4', 'RSINFO_1_LR_R_5', 'RSINFO_1_LR_R_6', 'RSINFO_1_LR_R_7', 'RSINFO_1_LR_R_8', 'RSINFO_1_LR_R_9', 'RSINFO_1_LR_R_10', 'RSINFO_1_LR_R_11', 'RSINFO_1_LR_R_12', 'RSINFO_1_LR_R_13', 'RSINFO_1_LR_R_14', 'RSINFO_2_LR_R_1', 'RSINFO_2_LR_R_2', 'RSINFO_2_LR_R_3', 'RSINFO_2_LR_R_4', 'RSINFO_2_LR_R_5', 'RSINFO_2_LR_R_6', 'RSINFO_2_LR_R_7', 'RSINFO_2_LR_R_8', 'RSINFO_2_LR_R_9', 'RSINFO_2_LR_R_10', 'RSINFO_2_LR_R_11', 'RSINFO_2_LR_R_12', 'RSINFO_2_LR_R_13', 'RSINFO_2_LR_R2_1', 'RSINFO_2_LR_R2_2', 'RSINFO_2_LR_R2_3', 'RSINFO_2_LR_R2_4', 'RSINFO_2_LR_R2_5', 'RSINFO_2_LR_R2_6', 'RSINFO_2_LR_R2_7', 'RSINFO_2_LR_R2_8', 'RSINFO_2_LR_R2_9', 'RSINFO_2_LR_R2_10', 'RSINFO_2_LR_R2_11', 'RSINFO_2_LR_R2_12', 'RSINFO_2_LR_R2_13', 'RSINFO_2_LR_R2_14', 'RSINFO_2_LR_R3_1', 'RSINFO_2_LR_R3_2', 'RSINFO_2_LR_R3_3', 'RSINFO_2_LR_R3_4', 'RSINFO_2_LR_R3_5', 'RSINFO_2_LR_R3_6', 'RSINFO_2_LR_R3_7', 'RSINFO_2_LR_R3_8', 'RSINFO_2_LR_R3_9', 'RSINFO_2_LR_R3_10', 'RSINFO_2_LR_R3_11', 'RSINFO_2_LR_R3_12', 'RSINFO_2_LR_R3_13', 'RSINFO_2_LR_R4_1', 'RSINFO_2_LR_R4_2', 'RSINFO_2_LR_R4_3', 'RSINFO_2_LR_R4_4', 'RSINFO_2_LR_R4_5', 'RSINFO_2_LR_R4_6', 'RSINFO_2_LR_R4_7', 'RSINFO_2_LR_R4_8', 'RSINFO_2_LR_R4_9', 'RSINFO_2_LR_R4_10', 'RSINFO_2_LR_R4_11', 'RSINFO_2_LR_R4_12', 'RSINFO_2_LR_R4_13', 'RSINFO_2_LR_R4_14', 'RSINFO_2_LR_R4_15', 'MOTIVRS_R_1', 'MOTIVRS_R_2', 'MOTIVRS_R_3', 'MOTIVRS_R_4', 'MOTIVRS_R_5', 'MOTIVRS_R_6', 'MOTIVRS_R_7', 'MOTIVRS_R_8', 'MOTIVRS_R_9', 'MOTIVRS_R_10', 'MOTIVRS_R_11', 'MOTIVRS_R_12', 'ENGAR_R_1', 'ENGAR_R_2', 'ENGAR_R_3', 'ENGAR_R_4', 'ENGAR_R2_1', 'ENGAR_R2_2', 'ENGAR_R2_3', 'ENGAR_R2_4', 'ENGAR_R3_1', 'ENGAR_R3_2', 'ENGAR_R3_3', 'ENGAR_R3_4', 'ENGAR_R4_1', 'ENGAR_R4_2', 'ENGAR_R4_3', 'ENGAR_R4_4', 'SOURCES1AR_B1_R_1', 'SOURCES1AR_B1_R_2', 'SOURCES1AR_B1_R_3', 'SOURCES1AR_B1_R_4', 'SOURCES1AR_B1_R_5', 'SOURCES1AR_B1_R_6', 'SOURCES1AR_B1_R_7', 'SOURCES1AR_B1_R_8', 'SOURCES1AR_B1_R_9', 'SOURCES1AR_B1_R_10', 'SOURCES1AR_B1_R_11', 'SOURCES1AR_B1_R_12', 'SOURCES1AR_B1_R_13', 'SOURCES1AR_B1_R_14', 'SOURCES1AR_B1_R_15', 'SOURCES1A_DOMR_R_1', 'SOURCES1A_DOMR_R_2', 'SOURCES1A_DOMR_R_3', 'SOURCES1A_DOMR_R_4', 'SOURCES1A_DOMR_R_5', 'SOURCES1A_DOMR_R_6', 'SOURCES1A_DOMR_R_7', 'SOURCES1A_DOMR_R_8', 'SOURCES1A_DOMR_R_9', 'SOURCES1A_DOMR_R_10', 'SOURCES1A_DOMR_R_11', 'SOURCES1A_DOMR_R_12', 'SOURCES1A_DOMR_R_13', 'SOURCES1A_DOMR_R_14', 'SOURCES1BR_B2_R_1', 'SOURCES1BR_B2_R_2', 'SOURCES1BR_B2_R_3', 'SOURCES1BR_B2_R_4', 'SOURCES1BR_B2_R_5', 'SOURCES1BR_B2_R_6', 'SOURCES1BR_B2_R_7', 'SOURCES1BR_B2_R_8', 'SOURCES1BR_B2_R_9', 'SOURCES1BR_B2_R_10', 'SOURCES1BR_B2_R_11', 'SOURCES1BR_B2_R_12', 'SOURCES1BR_B2_R_13', 'SOURCES1BR_B2_R_14', 'SOURCES1BR_B2_R_15', 'SOURCES1BR_B2_R_16', 'SOURCES1BR_B2_R_17', 'SOURCES1CR_B3_R_1', 'SOURCES1CR_B3_R_2', 'SOURCES1CR_B3_R_3', 'SOURCES1CR_B3_R_4', 'SOURCES1CR_B3_R_5', 'SOURCES1CR_B3_R_6', 'SOURCES1CR_B3_R_7', 'SOURCES1CR_B3_R_8', 'SOURCES1CR_B3_R_9', 'SOURCES1CR_B3_R_10', 'SOURCES1CR_B3_R_11', 'SOURCES1CR_B3_R_12', 'SOURCES1CR_B3_R_13', 'SOURCES1CR_B3_R_14', 'SOURCES1CR_B3_R_15', 'SOURCES1CR_B3_R_16', 'SOURCES1CR_B3_R_17', 'SOURCES1DR_B4_R_1', 'SOURCES1DR_B4_R_2', 'SOURCES1DR_B4_R_3', 'SOURCES1DR_B4_R_4', 'SOURCES1DR_B4_R_5', 'SOURCES1DR_B4_R_6', 'SOURCES1DR_B4_R_7', 'SOURCES1DR_B4_R_8', 'SOURCES1DR_B4_R_9', 'SOURCES1DR_B4_R_10', 'SOURCES1DR_B4_R_11', 'SOURCES1DR_B4_R_12', 'SOURCES1DR_B4_R_13', 'SOURCES1ER_B4_R_1', 'SOURCES1ER_B4_R_2', 'SOURCES1ER_B4_R_3', 'SOURCES1ER_B4_R_4', 'SOURCES1ER_B4_R_5', 'SOURCES1ER_B4_R_6', 'SOURCES1ER_B4_R_7', 'SOURCES1ER_B4_R_8', 'SOURCES1ER_B4_R_9', 'SOURCES1FR_R_1', 'SOURCES1FR_R_2', 'SOURCES1FR_R_3', 'SOURCES1FR_R_4', 'SOURCES1FR_R_5', 'SOURCES1FR_R_6', 'SOURCES1FR_R_7', 'SOURCES1FR_R_8', 'SOURCES1FR_R_9', 'SOURCES1FR_R_10', 'SOURCES1FR_R_11', 'SOURCES1FR_R_12', 'SOURCES1FR_R_13', 'SOURCES1FR_R_14', 'TV2AR_R_1', 'TV2AR_R_2', 'TV2AR_R_3', 'TV2AR_R_4', 'TV2AR_R_5', 'TV2AR_R_6', 'TV2AR_R_7', 'TV2AR_R_8', 'TV2AR_R_9', 'TV2AR_R_10', 'TV2AR_R_11', 'TV2BR_R_1', 'TV2BR_R_2', 'TV2BR_R_3', 'TV2BR_R_4', 'TV2BR_R_5', 'TV2BR_R_6', 'TV2BR_R_7', 'TV2BR_R_8', 'TV2BR_R_9', 'TV2BR_R_10', 'TV2BR_R_11', 'TV2BR_R_12', 'TV2BR_R_13', 'TV2BR_R_14', 'TV2CR_R_1', 'TV2CR_R_2', 'TV2CR_R_3', 'TV2CR_R_4', 'TV2CR_R_5', 'TV2CR_R_6', 'TV2CR_R_7', 'TV2CR_R_8', 'TV2CR_R_9', 'TV2CR_R_10', 'TV2CR_R_11', 'INF1_R_1', 'INF1_R_2', 'INF1_R_3', 'INF1_R_4', 'DYN1_R', 'DYN2_R_1', 'DYN2_R_2', 'DYN2_R_3', 'DYN2_R_4', 'DYN2_R_5', 'DYN2_R_6', 'DYN2_R_7', 'DYN2_R_8', 'DYN2_R_9', 'DYN2_R_10', 'DYN3_R_1', 'DYN3_R_2', 'DYN3_R_3', 'DYN3_R_4', 'DYN3_R_5', 'DYN3_R_6', 'DYN3_R_7', 'DYN3_R_8', 'EVITE1_R', 'EVITE2_R_1', 'EVITE2_R_2', 'EVITE2_R_3', 'EVITE2_R_4', 'EVITE2_R_5', 'EVITE2_R_6', 'EVITE2_R_7', 'EVITE2_R_8', 'EVITE2_R_9', 'CONF1_R', 'INF3_R_1', 'INF3_R_2', 'INF3_R_3', 'INF3_R_4', 'INF3_R_5', 'INF3_R_6', 'INF3_R_7', 'INF3_R_8', 'INF3_R_9', 'INF3_R1_1', 'INF3_R1_2', 'INF3_R1_3', 'INF3_R1_4', 'INF3_R1_5', 'INF3_R1_6', 'INF3_R1_7', 'INF3_R1_8', 'INF3_R1_9', 'INF3_R1_10', 'ATTSOURCES_R_1', 'ATTSOURCES_R_2', 'ATTSOURCES_R_3', 'ATTSOURCES_R_4', 'ATTSOURCES_R_5', 'ATTSOURCES_R_6', 'ATTSOURCES_R_7', 'ATTSOURCES_R1_1', 'ATTSOURCES_R1_2', 'ATTSOURCES_R1_3', 'ATTSOURCES_R1_4', 'ATTSOURCES_R1_5', 'ATTSOURCES_R1_6', 'ATTSOURCES_R1_7', 'ATTSOURCES_R1_8', 'INFOFIABLEDEF_R_1', 'INFOFIABLEDEF_R_2', 'INFOFIABLEDEF_R_3', 'INFOFIABLEDEF_R_4', 'INFOFIABLEDEF_R_5', 'INFOFIABLEDEF_R_6', 'INFOFIABLEDEF_R_7', 'INFOFIABLEDEF_R_8', 'INFOFIABLEDEF_R_9', 'INFOFIABLEDEF_R_10', 'INFOFIABLEDEF_R_11', 'INFOFIABLEDEF_R_12', 'INFOFIABLEDEF_R_13', 'INFOFIABLEDEF_R_14', 'INFOFIABLE_R', 'OP2_R_1', 'OP2_R_2', 'OP2_R_3', 'OP2_R_4', 'OP2_R1', 'OP2_R2_1', 'OP2_R2_2', 'OP2_R2_3', 'OP2_R2_4', 'OP2_R2_5', 'COMPLOT1_R_1', 'COMPLOT1_R_2', 'COMPLOT1_R_3', 'COMPLOT1_R_4', 'COMPLOT1_R_5', 'COMPLOT1_R_6', 'COMPLOT1_R_7', 'COMPLOT1_R_8', 'COMPLOT1_R1_1', 'COMPLOT1_R1_2', 'COMPLOT1_R1_3', 'COMPLOT1_R1_4', 'COMPLOT1_R1_5', 'COMPLOT1_R1_6', 'COMPLOT1_R1_7', 'COMPLOT1_R1_8', 'COMPLOT1_R1_9', 'COMPLOT2_R_1', 'COMPLOT2_R_2', 'COMPLOT2_R_3', 'COMPLOT2_R_4', 'COMPLOT2_R_5', 'COMPLOT2_R_6', 'COMPLOT2_R_7', 'COMPLOT2_R_8', 'COMPLOT2_R1_1', 'COMPLOT2_R1_2', 'COMPLOT2_R1_3', 'COMPLOT2_R1_4', 'COMPLOT2_R1_5', 'COMPLOT2_R1_6', 'COMPLOT2_R1_7', 'COMPLOT2_R1_8', 'COMPLOT2_R1_9', 'COMPLOT2_R2', 'VALEURJ_R_1', 'VALEURJ_R_2', 'VALEURJ_R_3', 'VALEURJ_R_4', 'VALEURJ_R_5', 'ATTENTESJ_R_1', 'ATTENTESJ_R_2', 'ATTENTESJ_R_3', 'ATTENTESJ_R_4', 'ATTENTESJ_R_5', 'ATTENTESJ_R_6', 'ATTENTESJ_R_7', 'ATTENTESJ_R_8', 'ATTENTESJ_R_9', 'ATTENTESJ_R1_1', 'ATTENTESJ_R1_2', 'ATTENTESJ_R1_3', 'ATTENTESJ_R1_4', 'ATTENTESJ_R1_5', 'ATTENTESJ_R1_6', 'ATTENTESJ_R1_7', 'ATTENTESJ_R1_8', 'ATTENTESJ_R1_9', 'ATTENTESJ_R1_10', 'ATTENTESJ_R2_1', 'ATTENTESJ_R2_2', 'ATTENTESJ_R2_3', 'ATTENTESJ_R2_4', 'ATTENTESJ_R2_5', 'ATTENTESJ_R2_6', 'ATTENTESJ_R2_7', 'ATTENTESJ_R2_8', 'ATTENTESJ_R2_9', 'ATTENTESJ_R2_10', 'ATTENTESJ_R3_1', 'ATTENTESJ_R3_2', 'ATTENTESJ_R3_3', 'ATTENTESJ_R3_4', 'ATTENTESJ_R3_5', 'ATTENTESJ_R3_6', 'ATTENTESJ_R3_7', 'ATTENTESJ_R3_8', 'ATTENTESJ_R3_9', 'ATTENTESJ_R3_10', 'ATTENTESJ_R4_1', 'ATTENTESJ_R4_2', 'ATTENTESJ_R4_3', 'ATTENTESJ_R4_4', 'ATTENTESJ_R4_5', 'ATTENTESJ_R4_6', 'ATTENTESJ_R4_7', 'ATTENTESJ_R4_8', 'ATTENTESJ_R4_9', 'ATTENTESJ_R4_10', 'DOUTE_R', 'DEFIANCEJ_R_1', 'DEFIANCEJ_R_2', 'DEFIANCEJ_R_3', 'DEFIANCEJ_R_4', 'DEFIANCEJ_R_5', 'DEFIANCEJ_R_6', 'DEFIANCEJ_R_7', 'DEFIANCEJ_R_8', 'DEFIANCEJ_R_9', 'DEFIANCEJ_R_10', 'DEFIANCEJ_R1_1', 'DEFIANCEJ_R1_2', 'DEFIANCEJ_R1_3', 'DEFIANCEJ_R1_4', 'DEFIANCEJ_R1_5', 'DEFIANCEJ_R1_6', 'DEFIANCEJ_R1_7', 'DEFIANCEJ_R1_8', 'DEFIANCEJ_R1_9', 'DEFIANCEJ_R1_10', 'DEFIANCEJ_R1_11', 'DEFIANCEJ_R2', 'CONNAISSALGOA_R_1', 'CONNAISSALGOA_R_2', 'CONNAISSALGOA_R_3', 'CONNAISSALGOA_R_4', 'CONNAISSALGOA_R_5', 'CONNAISSALGOA_R_6', 'CONNAISSALGOA_R1_1', 'CONNAISSALGOA_R1_2', 'CONNAISSALGOA_R1_3', 'CONNAISSALGOA_R1_4', 'CONNAISSALGOA_R1_5', 'CONNAISSALGOA_R1_6', 'CONNAISSALGOA_R1_7', 'CONNAISSALGOA_R2_1', 'CONNAISSALGOA_R2_2', 'CONNAISSALGOA_R2_3', 'CONNAISSALGOA_R2_4', 'CONNAISSALGOA_R2_5', 'CONNAISSALGOA_R2_6', 'CONNAISSALGOA_R2_7', 'CONNAISSALGOB_R_1', 'CONNAISSALGOB_R_2', 'CONNAISSALGOB_R_3', 'CONNAISSALGOB_R_4', 'CONNAISSALGOB_R_5', 'CONNAISSALGOB_R_6', 'CONNAISSALGOB_R1_1', 'CONNAISSALGOB_R1_2', 'CONNAISSALGOB_R1_3', 'CONNAISSALGOB_R1_4', 'CONNAISSALGOB_R1_5', 'CONNAISSALGOB_R1_6', 'CONNAISSALGOB_R1_7', 'CONNAISSALGOB_R2_1', 'CONNAISSALGOB_R2_2', 'CONNAISSALGOB_R2_3', 'CONNAISSALGOB_R2_4', 'CONNAISSALGOB_R2_5', 'CONNAISSALGOB_R2_6', 'CONNAISSALGOB_R2_7', 'CRAINTESALGOIA_R_1', 'CRAINTESALGOIA_R_2', 'CRAINTESALGOIA_R_3', 'CRAINTESALGOIA_R_4', 'CRAINTESALGOIA_R_5', 'CRAINTESALGOIA_R_6', 'CRAINTESALGOIA_R_7', 'CRAINTESALGOIA_R_8', 'SELECT_R', 'IA1_R', 'OPTI_R_1', 'OPTI_R_2', 'OPTI_R_3', 'OPTI_R_4', 'OPTI_R_5', 'OPTI_R_6', 'OPTI_R1_1', 'OPTI_R1_2', 'OPTI_R1_3', 'OPTI_R1_4', 'OPTI_R1_5', 'OPTI_R1_6', 'OPTI_R1_7', 'OPTI_R2_1', 'OPTI_R2_2', 'OPTI_R2_3', 'OPTI_R2_4', 'OPTI_R2_5', 'OPTI_R2_6', 'OPTI_R2_7', 'ATTA_R_1', 'ATTA_R_2', 'ATTA_R_3', 'ATTA_R_4', 'ATTA_R_5', 'ATTA_R_6', 'ATTA_R_7', 'ATTA_R_8', 'ATTA_R1_1', 'ATTA_R1_2', 'ATTA_R1_3', 'ATTA_R1_4', 'ATTA_R1_5', 'ATTA_R1_6', 'ATTA_R1_7', 'ATTA_R1_8', 'ATTA_R1_9', 'ATTA_R2_1', 'ATTA_R2_2', 'ATTA_R2_3', 'ATTA_R2_4', 'ATTA_R2_5', 'ATTA_R2_6', 'ATTA_R2_7', 'ATTA_R2_8', 'ATTA_R2_9', 'DEM_R_1', 'DEM_R_2', 'DEM_R_3', 'DEM_R_4', 'DEM_R1_1', 'DEM_R1_2', 'DEM_R1_3', 'DEM_R1_4', 'DEM_R1_5', 'DEM_R2_1', 'DEM_R2_2', 'DEM_R2_3', 'DEM_R2_4', 'DEM_R2_5', 'CONFINST_R_1', 'CONFINST_R_2', 'CONFINST_R_3', 'CONFINST_R_4', 'CONFINST_R_5', 'CONFINST_R_6', 'CONFINST_R_7', 'CONFINST_R_8', 'CONFINST_R_9', 'CONFINST_R_10', 'CONFINST_R1_1', 'CONFINST_R1_2', 'CONFINST_R1_3', 'CONFINST_R1_4', 'CONFINST_R1_5', 'CONFINST_R1_6', 'CONFINST_R1_7', 'CONFINST_R1_8', 'CONFINST_R1_9', 'CONFINST_R1_10', 'CONFINST_R1_11', 'CONFINST_R2_1', 'CONFINST_R2_2', 'CONFINST_R2_3', 'CONFINST_R2_4', 'CONFINST_R2_5', 'CONFINST_R2_6', 'CONFINST_R2_7', 'CONFINST_R2_8', 'CONFINST_R2_9', 'CONFINST_R2_10', 'CONFINST_R2_11', 'PERS_R_1', 'PERS_R_2', 'PERS_R_3', 'PERS_R_4', 'PERS_R_5', 'PERS_R_6', 'PERS_R1_1', 'PERS_R1_2', 'PERS_R1_3', 'PERS_R1_4', 'PERS_R1_5', 'PERS_R1_6', 'PERS_R1_7', 'INFLUENCE_R', 'VA1_R_1', 'VA1_R_2', 'VA1_R_3', 'VA1_R_4', 'VA1_R_5', 'VA1_R_6', 'VA1_R_7', 'VA1_R_8', 'VA1_R1_1', 'VA1_R1_2', 'VA1_R1_3', 'VA1_R1_4', 'VA1_R1_5', 'VA1_R1_6', 'VA1_R1_7', 'VA1_R1_8', 'VA1_R1_9', 'VA1_R2_1', 'VA1_R2_2', 'VA1_R2_3', 'VA1_R2_4', 'VA1_R2_5', 'VA1_R2_6', 'VA1_R2_7', 'VA1_R2_8', 'VA1_R2_9', 'NOU1_R', 'PP3_R', 'QUIZZ1_R', 'QUIZZ2_R', 'QUIZZ3_R', 'QUIZZ4_R', 'QUESTION_OUVERTE']
Nb colonnes : 1076

================================================================================
Nom : ina-csa-parole-femmes-chaines.csv
Colonnes : ['media', 'Editeur', 'group', 'nb_declarations_2020', 'total_declarations_duration_2020', 'women_speech_duration_2020', 'men_speech_duration_2020', 'other_duration_2020', 'women_expression_rate_2020', 'speech_rate_2020', 'nb_declarations_2019', 'total_declarations_duration_2019', 'women_speech_duration_2019', 'men_speech_duration_2019', 'other_duration_2019', 'women_expression_rate_2019', 'speech_rate_2019']
Nb colonnes : 17

================================================================================
Nom : 20190308-tv-years.csv
Colonnes : ['year', 'Médiane', 'Médiane privé', 'Médiane public', 'ARTE', 'Animaux', 'BFM TV', 'Canal+', 'Canal+ Sport', 'Chasse et pêche', 'Chérie 25', 'Comédie+', 'D8/C8', 'Euronews', 'Eurosport France', 'France 2', 'France 24', 'France 3', 'France 5', 'France O', 'Histoire', 'I-Télé/CNews', "L'Equipe 21", 'LCI', 'LCP/Public Sénat', 'La chaîne Météo', 'M6', 'Monte Carlo TMC', 'NRJ 12', 'Paris Première', 'Planète+', 'TF1', 'TV Breizh', 'TV5 Monde', "Toute l'Histoire", 'Téva', 'Voyage', 'W9']
Nb colonnes : 38

================================================================================
Nom : 2026-les-francais-et-linformation-2eme-edition-arcom-base-anonymisee-complete.csv

Explorer les 8 csv et le Excel pour comprendre les données, les variables, les types de données, les valeurs manquantes, les distributions, etc.

A priori 3 datasets sont à privilégier : les données de l'INA sur l'offre d'information, les données de l'INA sur les programmes, et les données de l'INA sur les audiences. 

Les données de l'ARCOM sont mises de côté pour l'instant, car elles sont plus difficiles à exploiter (format Excel, données moins structurées, etc.).

In [3]:
f = Path("../data/raw/20190308-stats.csv")
df = pd.read_csv(f)

In [4]:
df.head()

,media_type,channel_code,channel_name,is_public_channel,date,week_day,school_holiday_zones,civil_holyday,hour,male_duration,female_duration,music_duration
0,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,5,224.34,191.86,3180.34
1,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,11,160.68,137.90,3297.08
2,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,13,124.20,168.28,3303.96
3,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,18,251.20,185.58,3156.34
4,radio,CHE,Chérie FM,False,2001-01-02,Tuesday,ABC,False,6,550.76,223.60,2818.50

In [5]:
df.columns.to_list()

['media_type',
 'channel_code',
 'channel_name',
 'is_public_channel',
 'date',
 'week_day',
 'school_holiday_zones',
 'civil_holyday',
 'hour',
 'male_duration',
 'female_duration',
 'music_duration']

In [6]:
df.sample(10, random_state=42)

,media_type,channel_code,channel_name,is_public_channel,date,week_day,school_holiday_zones,civil_holyday,hour,male_duration,female_duration,music_duration
923635,tv,MTO,La chaîne Météo,False,2012-08-30,Thursday,ABC,False,15,2742.24,289.42,524.10
665128,tv,BFT,BFM TV,False,2011-11-09,Wednesday,NaN,False,23,1843.68,1230.24,441.76
356325,radio,NOS,Nostalgie,False,2007-01-20,Saturday,NaN,False,6,435.56,169.44,2992.30
743701,tv,C+8,D8/C8,False,2018-09-27,Thursday,NaN,False,13,1628.22,1551.02,338.78
503102,radio,RTL,RTL,False,2019-01-03,Thursday,ABC,False,6,1682.20,1798.26,107.36
1072362,tv,W9,W9,False,2015-11-09,Monday,NaN,False,22,1108.90,529.86,1753.72
325510,radio,NRJ,NRJ,False,2006-04-15,Saturday,BC,False,5,109.52,27.34,3445.74
888002,tv,E21,L'Equipe 21,False,2018-12-21,Friday,NaN,False,14,1862.84,922.36,753.58
139668,radio,FCR,France Culture,True,2019-01-12,Saturday,NaN,False,17,2153.66,1150.30,256.62
478933,radio,RTL,RTL,False,2004-12-01,Wednesday,NaN,False,21,3359.60,144.76,66.44

In [7]:
df['media_type'].value_counts(dropna=False)

media_type
radio    636822
tv       441979
Name: count, dtype: int64

In [8]:
df.groupby("media_type").size()

media_type
radio    636822
tv       441979
dtype: int64

In [10]:
df_tv=df[df["media_type"]=="tv"]
df_tv.shape

(441979, 12)

In [11]:
df_tv["channel_name"].value_counts().head(20)

channel_name
NRJ 12              16279
France 5            16270
I-Télé/CNews        16246
TF1                 16211
Monte Carlo TMC     16180
LCP/Public Sénat    16156
M6                  16148
Canal+              16108
LCI                 16107
W9                  16090
France 2            16089
BFM TV              16065
France 3            16021
ARTE                15976
France O            15716
Eurosport France    15264
France 24           14514
Histoire            13416
Téva                13231
D8/C8               11933
Name: count, dtype: int64

In [12]:
df_tv.duplicated(subset=["media_type", "channel_code", "date", "hour"]).sum()

np.int64(0)

In [13]:
df.duplicated(subset=["media_type", "channel_code", "date", "hour"]).sum()

np.int64(0)

In [14]:
df_tv.dtypes

media_type               object
channel_code             object
channel_name             object
is_public_channel          bool
date                     object
week_day                 object
school_holiday_zones     object
civil_holyday              bool
hour                      int64
male_duration           float64
female_duration         float64
music_duration          float64
dtype: object

In [15]:
df_tv.isna().sum()

media_type                   0
channel_code                 0
channel_name                 0
is_public_channel            0
date                         0
week_day                     0
school_holiday_zones    259698
civil_holyday                0
hour                         0
male_duration                0
female_duration              0
music_duration               0
dtype: int64

In [16]:
df_tv[["male_duration", "female_duration", "music_duration"]].describe()

       male_duration  female_duration  music_duration
count  441979.000000    441979.000000   441979.000000
mean     1953.957381       816.753642      702.746655
std       624.759041       527.072264      452.045752
min         0.000000         0.000000        0.000000
25%      1526.210000       400.200000      379.940000
50%      1937.060000       770.420000      615.400000
75%      2373.980000      1163.350000      929.080000
max      3598.200000      3470.240000     3599.980000

In [17]:
df_tv["hour"].value_counts().sort_index()

hour
10    31660
11    31742
12    31441
13    31698
14    31662
15    31699
16    31385
17    31432
18    31551
19    31484
20    31608
21    31434
22    31627
23    31556
Name: count, dtype: int64

In [18]:
df_tv["channel_name"].sort_values().unique()

array(['ARTE', 'Animaux', 'BFM TV', 'Canal+', 'Canal+ Sport',
       'Chasse et pêche', 'Chérie 25', 'Comédie+', 'D8/C8', 'Euronews',
       'Eurosport France', 'France 2', 'France 24', 'France 3',
       'France 5', 'France O', 'Histoire', 'I-Télé/CNews', "L'Equipe 21",
       'LCI', 'LCP/Public Sénat', 'La chaîne Météo', 'M6',
       'Monte Carlo TMC', 'NRJ 12', 'Paris Première', 'Planète+', 'TF1',
       'TV Breizh', 'TV5 Monde', "Toute l'Histoire", 'Téva', 'Voyage',
       'W9'], dtype=object)

In [19]:
df_tv["music_duration"].describe()

count    441979.000000
mean        702.746655
std         452.045752
min           0.000000
25%         379.940000
50%         615.400000
75%         929.080000
max        3599.980000
Name: music_duration, dtype: float64

In [20]:
df_tv["music_duration"].isna().sum()

np.int64(0)

Conclusions du fichier 20190308-stats.csv : 

Objectif potentiel
Analyser la représentation femmes / hommes dans les contenus télévisés.

Périmètre retenu
Le fichier source contient radio et TV. Pour rester cohérente avec le projet, l’analyse sera restreinte à la TV.

Granularité
Une ligne correspond à une combinaison unique :

media_type
channel_code
date
hour

Aucun doublon exact sur cette combinaison.

Taille de la sous-partie TV

441 979 lignes
12 colonnes

Colonnes principales

channel_code
channel_name
is_public_channel
date
hour
male_duration
female_duration
music_duration

Qualité des données

aucun doublon sur la granularité retenue
aucune valeur manquante sauf school_holiday_zones
date est encore au format object et devra être convertie

Remarques

la plage horaire observée va de 10 à 23
les chaînes publiques et privées sont présentes
France 2 est bien incluse dans les données

In [29]:
df_tv = df[df["media_type"] == "tv"].copy()

In [30]:
df_tv["date"] = pd.to_datetime(df_tv["date"])

In [31]:
df_tv["date"].min(), df_tv["date"].max()

(Timestamp('2010-01-01 00:00:00'), Timestamp('2019-02-28 00:00:00'))

Période couverte de 2010 à 2019

In [32]:
df_tv["is_public_channel"].value_counts()

is_public_channel
False    322067
True     119912
Name: count, dtype: int64

In [33]:
df_tv.groupby("is_public_channel")["channel_name"].nunique()

is_public_channel
False    26
True      8
Name: channel_name, dtype: int64

34 chaînes différentes dont 26 privées et 8 publiques
school_holiday_zones a bcp de valeurs manquantes, probablement à ignorer dans le cadre de ce projet

Création d'indicateurs potentiels sur la part féminine dans les programmes, la part masculine, etc.

In [ ]:
# Créer une durée totale genrée
df_tv["total_gender_duration"] = df_tv["male_duration"] + df_tv["female_duration"]
# Créer une part féminine
df_tv["female_share"] = df_tv["female_duration"] / df_tv["total_gender_duration"]
# Créer une part masculine
df_tv["male_share"] = df_tv["male_duration"] / df_tv["total_gender_duration"]
# Vérifier les nouvelles colonnes
df_tv[["male_duration", "female_duration", "total_gender_duration", "female_share", "male_share"]].head()

,male_duration,female_duration,total_gender_duration,female_share,male_share
636822,829.06,371.28,1200.34,0.309312,0.690688
636823,148.42,68.56,216.98,0.315974,0.684026
636824,1722.84,307.90,2030.74,0.151620,0.848380
636825,2714.88,329.62,3044.50,0.108267,0.891733
636826,1254.78,1243.14,2497.92,0.497670,0.502330

In [36]:
df_tv[["female_share", "male_share"]].describe()

        female_share     male_share
count  441949.000000  441949.000000
mean        0.296228       0.703772
std         0.180308       0.180308
min         0.000000       0.000000
25%         0.155600       0.580486
50%         0.287791       0.712209
75%         0.419514       0.844400
max         1.000000       1.000000

In [37]:
(df_tv["total_gender_duration"] == 0).sum()

np.int64(30)

In [38]:
df_tv[df_tv["total_gender_duration"] == 0][
    ["channel_name", "date", "hour", "male_duration", "female_duration", "music_duration", "total_gender_duration"]
].head(10)

,channel_name,date,hour,male_duration,female_duration,music_duration,total_gender_duration
638486,ARTE,2010-12-26,11,0.0,0.0,3427.98,0.0
638799,ARTE,2011-02-27,10,0.0,0.0,3231.40,0.0
639618,ARTE,2011-08-22,10,0.0,0.0,3597.74,0.0
669693,BFM TV,2014-08-21,10,0.0,0.0,0.00,0.0
669696,BFM TV,2014-08-21,23,0.0,0.0,0.00,0.0
706550,Chasse et pêche,2013-05-16,18,0.0,0.0,0.00,0.0
706551,Chasse et pêche,2013-05-16,19,0.0,0.0,0.00,0.0
727804,Comédie+,2014-05-10,19,0.0,0.0,0.00,0.0
727991,Comédie+,2014-07-20,22,0.0,0.0,0.00,0.0
787192,France 24,2012-01-16,22,0.0,0.0,1.06,0.0

In [39]:
df_tv["female_share"].isna().sum()

np.int64(30)

In [40]:
df_tv.groupby("is_public_channel")[["female_share", "male_share"]].mean()

                   female_share  male_share
is_public_channel
False                  0.283213    0.716787
True                   0.331186    0.668814

In [41]:
df_tv.groupby("channel_name")[["female_share", "male_share"]].mean().sort_values("female_share", ascending=False)

                  female_share  male_share
channel_name
Téva                  0.476624    0.523376
France 24             0.450817    0.549183
Chérie 25             0.422750    0.577250
M6                    0.412592    0.587408
TF1                   0.366946    0.633054
W9                    0.360063    0.639937
BFM TV                0.358243    0.641757
Animaux               0.349432    0.650568
I-Télé/CNews          0.344239    0.655761
France O              0.340071    0.659929
Euronews              0.338351    0.661649
France 2              0.337220    0.662780
LCI                   0.333126    0.666874
NRJ 12                0.325103    0.674897
France 3              0.315490    0.684510
France 5              0.313847    0.686153
TV Breizh             0.306393    0.693607
TV5 Monde             0.305786    0.694214
Monte Carlo TMC       0.301449    0.698551
LCP/Public Sénat      0.298434    0.701566
Comédie+              0.294075    0.705925
ARTE                  0.288780    0.711220
D8/C8                 0.281165    0.718835
Voyage                0.245411    0.754589
Paris Première        0.231698    0.768302
Canal+                0.226670    0.773330
Histoire              0.191836    0.808164
La chaîne Météo       0.190959    0.809041
Toute l'Histoire      0.188778    0.811222
Planète+              0.171372    0.828628
L'Equipe 21           0.158582    0.841418
Chasse et pêche       0.091340    0.908660
Eurosport France      0.076661    0.923339
Canal+ Sport          0.056709    0.943291

Une première comparaison entre chaînes publiques et privées montre que la part féminine moyenne est plus élevée sur les chaînes publiques (33,1 %) que sur les chaînes privées (28,3 %) sur le périmètre étudié.
Cette différence suggère une sous-représentation plus marquée des durées féminines sur les chaînes privées, selon l’indicateur construit.
Une analyse plus fine par chaîne montre toutefois des écarts importants à l’intérieur de chaque groupe.

In [42]:
df_tv.groupby("is_public_channel")[["female_share"]].agg(["mean", "median"])

                  female_share
                          mean    median
is_public_channel
False                 0.283213  0.273609
True                  0.331186  0.322531

In [43]:
df_tv.groupby("channel_name")[["female_share"]].agg(["mean", "median"]).sort_values(("female_share", "mean"), ascending=False)

                 female_share
                         mean    median
channel_name
Téva                 0.476624  0.474521
France 24            0.450817  0.457432
Chérie 25            0.422750  0.396073
M6                   0.412592  0.424167
TF1                  0.366946  0.362270
W9                   0.360063  0.364421
BFM TV               0.358243  0.365892
Animaux              0.349432  0.328878
I-Télé/CNews         0.344239  0.337170
France O             0.340071  0.339603
Euronews             0.338351  0.336405
France 2             0.337220  0.319240
LCI                  0.333126  0.323223
NRJ 12               0.325103  0.318883
France 3             0.315490  0.302816
France 5             0.313847  0.306419
TV Breizh            0.306393  0.308707
TV5 Monde            0.305786  0.291398
Monte Carlo TMC      0.301449  0.290997
LCP/Public Sénat     0.298434  0.285349
Comédie+             0.294075  0.258130
ARTE                 0.288780  0.268377
D8/C8                0.281165  0.246074
Voyage               0.245411  0.191302
Paris Première       0.231698  0.209092
Canal+               0.226670  0.207925
Histoire             0.191836  0.138594
La chaîne Météo      0.190959  0.145611
Toute l'Histoire     0.188778  0.124296
Planète+             0.171372  0.110582
L'Equipe 21          0.158582  0.100545
Chasse et pêche      0.091340  0.060757
Eurosport France     0.076661  0.029919
Canal+ Sport         0.056709  0.019396

Colonnes conservées pour l’analyse principale
channel_code
channel_name
is_public_channel
date
week_day
hour
male_duration
female_duration
music_duration
Colonnes dérivées
total_gender_duration
female_share
male_share
Colonnes secondaires / non prioritaires
school_holiday_zones
civil_holiday

EDA — 20190308-stats.csv
Le fichier contient des données radio et tv.
Pour ce projet, le périmètre retenu est tv uniquement.
Après filtrage, le dataset TV contient 441 979 lignes et 12 colonnes.
La période couverte va de 2010-01-01 à 2019-02-28.
La granularité observée est : une chaîne + une date + une heure.
Aucun doublon n’a été trouvé sur la combinaison media_type, channel_code, date, hour.
Les colonnes principales retenues sont :
channel_code
channel_name
is_public_channel
date
week_day
hour
male_duration
female_duration
music_duration
school_holiday_zones est considérée comme secondaire pour l’instant.
Un indicateur female_share a été construit à partir de male_duration et female_duration.
Sur ce périmètre, la part féminine moyenne est plus élevée sur les chaînes publiques que sur les chaînes privées.
30 lignes ont une durée genrée totale nulle, ce qui rend la part non calculable sur ces cas.