Tri analytique des données des autres fichiers csv après les 2 principaux qui sont stats et ina-barometre-jt.

In [2]:
import pandas as pd

D'abord le fichier 20190308-years.csv qui contient des données sur les années de diffusion des émissions.

In [3]:
df = pd.read_csv(
    "../data/raw/20190308-years.csv")
df.head()

,media_type,channel_name,is_public_channel,year,women_expression_rate,speech_rate,nb_hours_analyzed
0,radio,Chérie FM,False,2002,47.109944,15.738694,718.0
1,radio,Chérie FM,False,2003,46.034445,16.250258,1617.0
2,radio,Chérie FM,False,2004,48.383607,15.035450,1644.0
3,radio,Chérie FM,False,2005,45.451627,16.063778,1624.0
4,radio,Chérie FM,False,2006,47.819307,15.602842,1604.0

Fichier déjà agrégé donc avec indicateurs présents => bon pour comparaison avec mes propres indicateurs que je vais créer. Utile pour validation de mes propres indicateurs et pour faire des analyses comparatives.

Fichier 20190308-tv-years.csv

In [4]:
df = pd.read_csv(
    "../data/raw/20190308-tv-years.csv")
df.head()

,year,Médiane,Médiane privé,Médiane public,ARTE,Animaux,BFM TV,Canal+,Canal+ Sport,Chasse et pêche,...,NRJ 12,Paris Première,Planète+,TF1,TV Breizh,TV5 Monde,Toute l'Histoire,Téva,Voyage,W9
0,2010,28.456112,29.061640,28.142902,28.142902,25.907573,38.657281,21.511909,5.972954,7.191762,...,30.924828,24.836079,17.715350,32.378823,NaN,28.028683,17.860130,NaN,23.647660,30.842987
1,2011,28.699712,28.137378,29.355850,28.066215,31.552513,36.924738,22.158304,5.532296,8.144227,...,27.400619,25.521252,15.799666,34.654424,29.884164,28.699712,20.773158,44.837283,25.008988,32.866201
2,2012,30.304361,30.304361,30.132021,29.943392,34.931348,35.418503,22.350216,5.211815,7.018204,...,32.673526,21.009000,16.061341,35.938752,29.347189,28.571516,19.347722,43.833923,24.327631,32.190639
3,2013,30.029029,29.597516,30.434711,27.587263,33.738746,35.811553,23.414536,4.944378,10.098884,...,30.674707,22.519630,15.655507,36.484382,29.939320,30.118738,17.219156,45.762380,26.818150,34.937838
4,2014,30.548617,30.734421,30.395366,29.091073,33.908685,33.319117,22.123673,5.095776,10.310289,...,35.244558,22.321418,17.282679,36.730678,30.173382,29.505054,19.644503,46.721922,24.428791,36.408688

Fichier déjà agrégé également, format large donc pas pratique car une ligne = une année et les indicateurs sont en colonnes. Je vais devoir faire du pivot pour le mettre en format long et pouvoir faire des analyses comparatives avec mes propres indicateurs que je vais créer.

In [5]:
df.shape

(10, 38)

Passons à 20190308-hourstall.csv

In [6]:
df = pd.read_csv(
    "../data/raw/20190308-hourstatall.csv")
df.head()

,media_type,channel_name,is_public_channel,year,hour,women_expression_rate,speech_rate,nb_hours_analyzed
0,radio,Chérie FM,False,2002,5,59.743802,17.874993,28.0
1,radio,Chérie FM,False,2002,6,55.012948,26.427162,20.0
2,radio,Chérie FM,False,2002,8,53.777281,30.158546,25.0
3,radio,Chérie FM,False,2002,11,39.891461,12.533961,21.0
4,radio,Chérie FM,False,2002,13,48.868789,16.901816,23.0

20190308-hourstall.csv contient des indicateurs déjà agrégés, avec une granularité plus fine que 20190308-years.csv grâce à la variable hour. Il peut servir de point de comparaison ou de validation horaire, mais il n’est pas retenu comme source principale, car 20190308-stats.csv fournit déjà une granularité plus brute (chaîne + date + heure).

Passons à ina-csa-parole-femmes-chaines.csv

In [7]:
df = pd.read_csv(
    "../data/raw/ina-csa-parole-femmes-chaines.csv")
df.head()

,media,Editeur,group,nb_declarations_2020,total_declarations_duration_2020,women_speech_duration_2020,men_speech_duration_2020,other_duration_2020,women_expression_rate_2020,speech_rate_2020,nb_declarations_2019,total_declarations_duration_2019,women_speech_duration_2019,men_speech_duration_2019,other_duration_2019,women_expression_rate_2019,speech_rate_2019
0,radio,Europe 1,Lagardère Active,3602.0,14877545.46,5432042.70,8220712.70,1224790.06,0.397872,0.917675,1684.0,9823492.72,3658937.50,5239559.62,924995.60,0.411186,0.905838
1,radio,Fip,Radio France,199.0,5270382.76,154044.20,64874.40,5051464.16,0.703660,0.041538,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,radio,France Culture,Radio France,2689.0,6933822.84,2357921.72,3762353.06,813548.06,0.385264,0.882670,2816.0,6959811.16,2309011.64,3907866.70,742932.82,0.371410,0.893254
3,radio,France Info,Radio France,850.0,7416247.18,2161868.06,4782895.82,471483.30,0.311295,0.936426,853.0,7020833.94,2075132.98,4541026.20,404674.76,0.313646,0.942361
4,radio,France Inter,Radio France,3707.0,8577861.92,2801560.84,4334779.34,1441521.74,0.392577,0.831949,3505.0,8298411.00,2532256.62,4415065.80,1351088.58,0.364494,0.837187

Pareil que les autres, déjà très transformé et format large. Chaque ligne correspond à une chaîne ou un éditeur, avec plusieurs indicateurs calculés pour 2019 et 2020. Le fichier contient à la fois radio et TV.
Il peut servir de fichier de validation ou d’enrichissement, mais il n’est pas retenu comme source principale du pipeline car les indicateurs sont déjà construits.

Et enfin : ina-csa-parole-femmes-genres.csv

In [8]:
df = pd.read_csv(
    "../data/raw/ina-csa-parole-femmes-genreprogramme.csv")
df.head()

,genre,nb_declarations_2020,total_declarations_duration_2020,women_speech_duration_2020,men_speech_duration_2020,other_duration_2020,women_expression_rate_2020,speech_rate_2020,nb_declarations_2019,total_declarations_duration_2019,women_speech_duration_2019,men_speech_duration_2019,other_duration_2019,women_expression_rate_2019,speech_rate_2019
0,Information - Journal,11770,31573605.20,10733020.96,16666252.56,4174331.68,0.391726,0.867790,12172.0,46426696.82,15227561.64,23912775.34,7286359.84,0.389050,0.843057
1,Information - Magazine,8839,43921146.18,12265253.54,28520630.38,3135262.26,0.300723,0.928616,10773.0,53435793.92,14629241.66,33703544.66,5103007.60,0.302677,0.904502
2,Information - Autres émissions,475,873112.46,286694.28,489202.08,97216.10,0.369501,0.888656,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Documentaire,737,2471803.82,710360.96,1159896.78,601546.08,0.379820,0.756637,521.0,1834222.64,537780.72,947300.84,349141.08,0.362122,0.809652
4,Magazine,18189,56430421.82,18222632.14,28479390.24,9728399.44,0.390189,0.827604,15113.0,45898496.56,14600771.90,24428136.00,6869588.66,0.374101,0.850331

Très petit, déjà agrégé, format large, utile pour validation.

In [9]:
df.columns

Index(['genre', 'nb_declarations_2020', 'total_declarations_duration_2020',
       'women_speech_duration_2020', 'men_speech_duration_2020',
       'other_duration_2020', 'women_expression_rate_2020', 'speech_rate_2020',
       'nb_declarations_2019', 'total_declarations_duration_2019',
       'women_speech_duration_2019', 'men_speech_duration_2019',
       'other_duration_2019', 'women_expression_rate_2019',
       'speech_rate_2019'],
      dtype='object')

Les fichiers arcom sont laissé de côté car moins adaptés pour mon pipeline que les fichiers INA. Mais à voir par la suite comme source complémentaire potentielle.

Synthèse de sélection des fichiers
Sources principales retenues
20190308-stats.csv
ina-barometre-jt-tv-donnees-quotidiennes-2000-2020-nbre-sujets-durees-202410.csv
Sources secondaires / validation
20190308-years.csv
20190308-hourstall.csv
20190308-tv-years.csv
ina-csa-parole-femmes-chaines.csv
ina-csa-parole-femmes-genreprogramme.csv
Sources écartées à ce stade
2026-les-francais-et-linformation-2eme-edition-arcom-base-anonymisee-complete.csv
les-francais-et-l-information-arcom-2024-base-anonymisee.xlsx