In [5]:
import pandas as pd

jt_year_theme = pd.read_csv("../data/processed/jt_topics_by_year_theme.csv")
jt_year_channel_theme = pd.read_csv("../data/processed/jt_topics_by_year_channel_theme.csv")

In [6]:
jt_year_theme.head()
jt_year_channel_theme.head()

   year channel_name            theme  total_subjects  total_duration  n_days
0  2000         Arte     Catastrophes             133            9328     104
1  2000         Arte  Culture-loisirs             313           53981     253
2  2000         Arte         Economie             308           34342     190
3  2000         Arte        Education              25            3641      21
4  2000         Arte    Environnement             123           15859     103

In [7]:
top_themes_global = (
    jt_year_theme.groupby("theme", as_index=False)
    .agg(
        total_subjects_all_years=("total_subjects", "sum"),
        total_duration_all_years=("total_duration", "sum"),
    )
    .sort_values("total_subjects_all_years", ascending=False)
)

top_themes_global.head(10)

               theme  total_subjects_all_years  total_duration_all_years
12           Société                    108039                   9829932
7      International                    103299                   8531221
9   Politique France                     51716                   4788726
2           Economie                     50529                   5012040
1    Culture-loisirs                     44071                   4773551
13             Sport                     40943                   2912559
0       Catastrophes                     37126                   2793608
8            Justice                     32176                   2671773
10             Santé                     30242                   2985161
4      Environnement                     26166                   2346820

In [8]:
top_themes_global.sort_values("total_duration_all_years", ascending=False).head(10)

               theme  total_subjects_all_years  total_duration_all_years
12           Société                    108039                   9829932
7      International                    103299                   8531221
2           Economie                     50529                   5012040
9   Politique France                     51716                   4788726
1    Culture-loisirs                     44071                   4773551
10             Santé                     30242                   2985161
13             Sport                     40943                   2912559
0       Catastrophes                     37126                   2793608
8            Justice                     32176                   2671773
4      Environnement                     26166                   2346820

In [9]:
top_themes_by_channel = (
    jt_year_channel_theme.groupby(["channel_name", "theme"], as_index=False)
    .agg(
        total_subjects_all_years=("total_subjects", "sum"),
        total_duration_all_years=("total_duration", "sum"),
    )
)

top5_by_channel = (
    top_themes_by_channel.sort_values(
        ["channel_name", "total_subjects_all_years"],
        ascending=[True, False]
    )
    .groupby("channel_name")
    .head(5)
)

top5_by_channel

,channel_name,theme,total_subjects_all_years,total_duration_all_years
7,Arte,International,34745,3065060
12,Arte,Société,9889,947051
1,Arte,Culture-loisirs,6122,825080
2,Arte,Economie,4737,465117
8,Arte,Justice,3504,279335
26,France 2,Société,29311,2848467
21,France 2,International,24712,1994492
23,France 2,Politique France,15642,1492680
16,France 2,Economie,14899,1591559
27,France 2,Sport,12120,853028
40,France 3,Société,19089,1799341
35,France 3,International,14988,1269070
37,France 3,Politique France,11284,1049295
30,France 3,Economie,9154,925106
28,France 3,Catastrophes,7227,557037
54,M6,Société,18965,1400193
49,M6,International,10317,636371
43,M6,Culture-loisirs,8884,778533
51,M6,Politique France,8397,636522
55,M6,Sport,8323,481730
68,TF1,Société,30785,2834880
63,TF1,International,18537,1566228
58,TF1,Economie,14788,1470262
65,TF1,Politique France,13158,1295604
69,TF1,Sport,12708,992827