In [1]:
import pandas as pd

In [4]:
import pandas as pd

pd.read_csv("../data/processed/tv_gender_stats_clean.csv").head()

,channel_code,channel_name,is_public_channel,date,week_day,hour,male_duration,female_duration,music_duration,total_gender_duration,female_share,male_share
0,ART,ARTE,True,2010-01-01,Friday,12,829.06,371.28,2056.80,1200.34,0.309312,0.690688
1,ART,ARTE,True,2010-01-01,Friday,14,148.42,68.56,2993.40,216.98,0.315974,0.684026
2,ART,ARTE,True,2010-01-01,Friday,18,1722.84,307.90,1238.96,2030.74,0.151620,0.848380
3,ART,ARTE,True,2010-01-01,Friday,21,2714.88,329.62,286.16,3044.50,0.108267,0.891733
4,ART,ARTE,True,2010-01-02,Saturday,11,1254.78,1243.14,1070.86,2497.92,0.497670,0.502330

In [5]:
pd.read_csv("../data/processed/jt_topics_clean.csv").head()

         date channel_name            theme  nb_subjects  duration
0  2000-01-02     France 3     Catastrophes            2       235
1  2000-01-02     France 3  Culture-loisirs            1       138
2  2000-01-02     France 3    Environnement            3       306
3  2000-01-02     France 3    International            2       241
4  2000-01-02     France 3          Société            2       160

In [6]:
pd.read_csv("../data/processed/tv_gender_by_year_channel.csv").head()

,year,channel_name,is_public_channel,avg_female_share,avg_male_share,total_female_duration,total_male_duration,n_obs
0,2010,ARTE,True,0.277246,0.722754,1164577.44,2973508.34,1698
1,2010,Animaux,False,0.258363,0.741637,644920.54,1844392.34,923
2,2010,BFM TV,False,0.387025,0.612975,2013958.76,3195819.92,1674
3,2010,Canal+,False,0.222122,0.777878,909338.40,3317801.08,1661
4,2010,Canal+ Sport,False,0.068735,0.931265,172028.70,2708098.84,990

In [7]:
pd.read_csv("../data/processed/jt_topics_by_year_channel_theme.csv").head()

   year channel_name            theme  total_subjects  total_duration  n_days
0  2000         Arte     Catastrophes             133            9328     104
1  2000         Arte  Culture-loisirs             313           53981     253
2  2000         Arte         Economie             308           34342     190
3  2000         Arte        Education              25            3641      21
4  2000         Arte    Environnement             123           15859     103